// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as Style$ReactNative from "reason-react-native/src/apis/Style.bs.js";

function ElevatedContainer(Props) {
  var children = Props.children;
  var containerStyle = Props.containerStyle;
  return React.createElement(ReactNative.View, {
              style: [
                {
                  backgroundColor: "#cccccc",
                  elevation: 10,
                  shadowColor: "rgba(0,0,0, .1)",
                  shadowOffset: {
                    height: -0.5,
                    width: 0
                  },
                  shadowOpacity: 1,
                  shadowRadius: 1,
                  padding: 16,
                  width: Style$ReactNative.pct(100)
                },
                containerStyle
              ],
              children: children !== undefined ? Caml_option.valFromOption(children) : null
            });
}

var make = ElevatedContainer;

export {
  make ,
  
}
/* react Not a pure module */
