// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";

function BlylContentView(Props) {
  var children = Props.children;
  var containerStyle = Props.containerStyle;
  var contentContainerStyle = Props.contentContainerStyle;
  var tmp = {
    showsHorizontalScrollIndicator: false,
    showsVerticalScrollIndicator: false,
    style: [
      {
        paddingHorizontal: 16
      },
      containerStyle
    ],
    children: children !== undefined ? Caml_option.valFromOption(children) : null
  };
  if (contentContainerStyle !== undefined) {
    tmp.contentContainerStyle = Caml_option.valFromOption(contentContainerStyle);
  }
  return React.createElement(ReactNative.ScrollView, tmp);
}

var make = BlylContentView;

export {
  make ,
  
}
/* react Not a pure module */
