// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";

function BlylView(Props) {
  var children = Props.children;
  var containerStyle = Props.containerStyle;
  return React.createElement(ReactNative.View, {
              style: [
                {
                  paddingHorizontal: 16
                },
                containerStyle
              ],
              children: children !== undefined ? Caml_option.valFromOption(children) : null
            });
}

var make = BlylView;

export {
  make ,
  
}
/* react Not a pure module */
