// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as BlylView from "../../blylView/components/BlylView.bs.js";
import * as ReactNative from "react-native";

function BlylSelection(Props) {
  var name = Props.name;
  var isActive = Props.isActive;
  var onSelect = Props.onSelect;
  return React.createElement(BlylView.make, {
              children: React.createElement(ReactNative.TouchableOpacity, {
                    style: {
                      flexDirection: "row",
                      justifyContent: "space-between",
                      width: 200
                    },
                    onPress: (function (param) {
                        return Curry._1(onSelect, name);
                      }),
                    children: null
                  }, React.createElement(ReactNative.Text, {
                        style: {
                          fontSize: 20
                        },
                        children: name
                      }), isActive ? React.createElement(ReactNative.View, {
                          style: {
                            borderRadius: 25
                          },
                          children: React.createElement(ReactNative.Image, {
                                source: require("../../../../assets/icons/doneIcon.png"),
                                style: [
                                  {
                                    height: 25,
                                    width: 25
                                  },
                                  {
                                    resizeMode: "contain"
                                  }
                                ]
                              })
                        }) : null),
              containerStyle: {
                alignItems: "center"
              }
            });
}

var make = BlylSelection;

export {
  make ,
  
}
/* react Not a pure module */
