// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as ReactNativeSafeAreaContext from "react-native-safe-area-context";

function BlylScreen(Props) {
  var children = Props.children;
  var insets = ReactNativeSafeAreaContext.useSafeArea();
  return React.createElement(ReactNative.View, {
              style: {
                backgroundColor: "#e6e6e6",
                flex: 1,
                justifyContent: "space-between",
                paddingBottom: insets.bottom,
                paddingTop: insets.top
              },
              children: children !== undefined ? Caml_option.valFromOption(children) : null
            });
}

var make = BlylScreen;

export {
  make ,
  
}
/* react Not a pure module */
