// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactNative from "react-native";

function BlylButton(Props) {
  var kindOpt = Props.kind;
  var title = Props.title;
  var onPress = Props.onPress;
  var buttonStyle = Props.buttonStyle;
  var titleStyle = Props.titleStyle;
  var kind = kindOpt !== undefined ? kindOpt : /* primary */58474434;
  return React.createElement(ReactNative.TouchableHighlight, {
              style: [
                {
                  borderWidth: 5,
                  alignItems: "center",
                  paddingHorizontal: 22,
                  paddingVertical: 10
                },
                kind >= 58474434 ? ({
                      backgroundColor: "#ffd633",
                      borderColor: "#1a1400"
                    }) : ({
                      backgroundColor: "#1a1400",
                      borderColor: "#ffd633"
                    }),
                buttonStyle
              ],
              onPress: (function (param) {
                  return Curry._1(onPress, /* () */0);
                }),
              children: React.createElement(ReactNative.Text, {
                    style: [
                      {
                        fontSize: 16,
                        fontWeight: "bold"
                      },
                      kind >= 58474434 ? ({
                            color: "#1a1400"
                          }) : ({
                            color: "#ffd633"
                          }),
                      titleStyle
                    ],
                    children: title
                  })
            });
}

var make = BlylButton;

export {
  make ,
  
}
/* react Not a pure module */
