// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

var defaultSize = {
  height: 180,
  width: 380
};

function BlylCard(Props) {
  var kind = Props.kind;
  var containerSizeOpt = Props.containerSize;
  var containerStyle = Props.containerStyle;
  var containerSize = containerSizeOpt !== undefined ? containerSizeOpt : defaultSize;
  return React.createElement(ReactNative.View, {
              children: React.createElement(ReactNative.Image, {
                    source: {
                      uri: kind >= 5544550 ? (
                          kind !== 5742370 ? (
                              kind >= 5795212 ? (
                                  kind >= 261117022 ? "https://i.ibb.co/j6pL78D/three.png" : "https://i.ibb.co/QC4Sd1F/two.png"
                                ) : (
                                  kind >= 5791197 ? "https://i.ibb.co/RvbtnPk/ten.png" : "https://i.ibb.co/GnWSjJC/one.png"
                                )
                            ) : "https://i.ibb.co/pWdjZb5/six.png"
                        ) : (
                          kind !== -1010801690 ? (
                              kind >= -315719345 ? (
                                  kind >= -97442547 ? "https://i.ibb.co/fpTLyLc/seven.png" : "https://i.ibb.co/yNK3mWm/eight.png"
                                ) : (
                                  kind >= -922385102 ? "https://i.ibb.co/hy8MYrb/nine.png" : "https://i.ibb.co/g91m3Vm/five.png"
                                )
                            ) : "https://i.ibb.co/k2ySvNd/four.png"
                        )
                    },
                    style: [
                      {
                        height: containerSize.height,
                        width: containerSize.width
                      },
                      containerStyle,
                      {
                        resizeMode: "stretch"
                      }
                    ]
                  })
            });
}

var imageDefault = {
  one: "https://i.ibb.co/GnWSjJC/one.png",
  two: "https://i.ibb.co/QC4Sd1F/two.png",
  three: "https://i.ibb.co/j6pL78D/three.png",
  four: "https://i.ibb.co/k2ySvNd/four.png",
  five: "https://i.ibb.co/g91m3Vm/five.png",
  six: "https://i.ibb.co/pWdjZb5/six.png",
  seven: "https://i.ibb.co/fpTLyLc/seven.png",
  eight: "https://i.ibb.co/yNK3mWm/eight.png",
  nine: "https://i.ibb.co/hy8MYrb/nine.png",
  ten: "https://i.ibb.co/RvbtnPk/ten.png"
};

var make = BlylCard;

export {
  defaultSize ,
  imageDefault ,
  make ,
  
}
/* react Not a pure module */
